name: Maven Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '7'
          distribution: 'temurin'
          cache: maven
          server-id: repsy
          server-username: REPSY_USER
          server-password: REPSY_TOKEN

      - name: Build with Maven
        run: ./mvnw -B deploy --file pom.xml